### ISSUE TITLE
Possible null pointer exception (CWE-476)

### ISSUE THREAD

**Issue by AppChecker** [ihongs/HongsCORE#1]
Hello!
Please look these code fragments:
1) [hongs-core/src/main/java/app/hongs/util/Batch.java](https://github.com/ihongs/HongsCORE/blob/d8491fa9f067af8904832f764e815ce11b0c1785/hongs-core/src/main/java/app/hongs/util/Batch.java#L82-L84)
```
if (back == null) {
  if (!tasks.isEmpty()) {
      CoreLogger.error("There has "+ tasks.size() +" task(s) not run in '"+back.getPath()+"'.");
```
if back is null and tasks is not empty  method back.getPath will be called -> NPE is happened.

2) [hongs-core/src/main/java/app/hongs/util/Async.java#L67-L69](https://github.com/ihongs/HongsCORE/blob/d8491fa9f067af8904832f764e815ce11b0c1785/hongs-core/src/main/java/app/hongs/util/Async.java#L67-L69)
Similar

This possible defects found by [AppChecker](https://npo-echelon.ru/en/solutions/appchecker.php)

**Comment by ihongs** [comment]
Thank you. I fixed it in the latest version.
